name: Push changes to dev repo folder
run-name: ${{ gitea.actor }} is building frontend 🚀
on:
  push:
    branches:
      - development

jobs:
  Building-Angular-Frontend:
    runs-on: linux_host
    steps:
      - uses: actions/checkout@v3
      - name: Current git remotes
        run: git remote -v
      - name: Push files to dev repo folder
        run: git remote add devwsys ssh://${{ secrets.HOST }}:${{ secrets.TARGET_FOLDER }}; git push devwsys development:development
      - run: echo "🍏 This job's status is ${{ job.status }}."
