name: Push changes to dev repo folder
run-name: ${{ gitea.actor }} is building frontend 🚀
on:
  push:
    branches:
      - development

jobs:
  Building-Angular-Frontend:
    runs-on: linux_host
    steps:
      - uses: actions/checkout@v3
      - name: Log into dev.wsys, pull changes and build project
        run: ssh ${{ secrets.HOST }} "cd ${{ secrets.TARGET_FOLDER }}; git pull; npm run build-storybook;"
      - run: echo "🍏 This job's status is ${{ job.status }}."
