name: Push changes to dev repo folder
run-name: ${{ gitea.actor }} is building frontend 🚀
on:
  push:
    branches:
      - development

jobs:
  Building-Angular-Frontend:
    runs-on: linux_host
    steps:
      - uses: actions/checkout@v3
      - name: Push files to dev repo folder
        run: git remote add dev-wsys ssh://${{ secrets.HOST }}:${{ secrets.TARGET_FOLDER }}; git pull dev-wsys development:development; git push dev-wsys development:development
      - name: Log into dev.wsys and build project
        run: ssh ${{ secrets.HOST }} "cd ${{ secrets.TARGET_FOLDER }}; npm run build-storybook;"
      - run: echo "🍏 This job's status is ${{ job.status }}."
